name: BloxTools
version: '${project.version}'
main: me.mrbloxman43.bloxtools.BloxTools
api-version: 1.18
authors: [ MrBloxMan43, cats585 ]
description: Plugin to help your minecraft server with some basic addons like essentials!
website: https://github.com/RandomKittenCat/BloxTools
commands:
  btinfo:
    description: Some description about the plugin.
    usage: /<command>
    permission: bloxtools.info
    permission-message: You don't have permission!
  flowerbadge:
    description: Gives someone a cool sunflower badge!
    usage: /<command>
    aliases: [sunflowerbadge, badge, fbadge]
    permission: bloxtools.flowerbadge
    permission-message: You don't have permission!
  feed:
    description: Gives yourself or others full hunger bars
    usage: /<command> [player]
    aliases: [btfeed]
    permission: bloxtools.feed
    permission-message: You don't have permission!
  heal:
    description: Gives you or others back full hearts
    usage: /<command> [player]
    aliases: [btheal]
    permission: bloxtools.heal
    permission-message: You don't have permission!
  kill:
    description: Kills the given player
    usage: /<command> {player}
    aliases: [btkill]
    permission: bloxtools.kill
    permission-message: You don't have permission!
