name: BloxTools
version: '${project.version}'
main: me.mrbloxman43.bloxtools.BloxTools
api-version: 1.18
authors: [ MrBloxMan43, cats585 ]
description: Plugin to help your minecraft server with some basic addons like essentials!
website: https://github.com/RandomKittenCat/BloxTools
commands:
  btinfo:
    description: Some description about the plugin.
    usage: /<command>
    permission: bloxtools.info
    permission-message: You don't have permission!
  flowerbadge:
    description: Gives someone a cool sunflower badge!
    usage: /<command>
    permission: bloxtools.flowerbadge
    permission-message: You don't have permissions!