name: BloxTools
version: '1.0-SNAPSHOT'
main: me.mrbloxman.bloxtools.BloxTools
api-version: '1.20'
website: https://github.com/RandomKittenCat/BloxTools
authors: [ MrBloxMan, cats585, RandomKittenCat ]
description: Useful plugin to give you access to various commands ingame
commands:
  btinfo:
    description: Source code link and maintain information
    usage: /<command>
  heal:
    description: Heal a players hearts to full
    usage: /<command> [player]
    permission: bloxtools.heal
    permission-message: "§cYou don't have permission to use this command!"
  gmc:
    description: Set gamemode to creative
    usage: /<command> [player]
    permission: bloxtools.creative
    permission-message: "§cYou don't have permission to use this command!"
    aliases: [creative, gmcreative, gm1]
  gms:
    description: Set gamemode to survival
    usage: /<command> [player]
    permission: bloxtools.survival
    permission-message: "§cYou don't have permission to use this command!"
    aliases: [survival, gmsurvival, gm2]
  gmsp:
    description: Set gamemode to spectator
    usage: /<command> [player]
    permission: bloxtools.spectator
    permission-message: "§cYou don't have permission to use this command!"
    aliases: [spectator, gmspectator, gm3]
  kill:
    description: Kills the player specified
    usage: /<command> [player]
    permission: bloxtools.kill
    permission-message: "§cYou don't have permission to use this command!"
  feed:
    description: Restores a players hunger bar
    usage: /<command> [player]
    permission: bloxtools.feed
    permission-message: "§cYou don't have permission to use this command!"
  weather:
    description: Sets the weather of the world
    usage: /<command> [weathertype]
    permission: bloxtools.weather
    permission-message: "§cYou don't have permission to use this command!"
  time:
    description: Set the time of the world
    usage: /<command> [time]
    permission: bloxtools.time
    permission-message: "§cYou don't have permission to use this command!"
  coords:
    description: Displays your coordinates in chat
    usage: /<command>
    permission: bloxtools.coords
    permission-message: "§cYou don't have permission to use this command!"
    aliases: [coordinates, location, whereami]
  forecast:
    description: Displays the current weather type in chat
    usage: /<command>
    permission: bloxtools.forecast
    permission-message: "§cYou don't have permission to use this command!"
  checktime:
    description: Check the current in-game time
    usage: /<command>
    permission: bloxtools.checktime
    permission-message: "§cYou don't have permission to use this command!"
    aliases: [gettime, checkwatch]
  spawn:
    description: Teleports the player to spawn
    usage: /<command> [player]
    permission: bloxtools.spawn
    permission-message: "§cYou don't have permission to use this command!"
  spawnmob:
    description: Spawn an entity at your location
    usage: /<command> <mobtype> [amount]
    permission: bloxtools.spawnmob
    permission-message: "§cYou don't have permission to use this command!"
  repair:
    description: Repair the current item in your hand
    usage: /<command>
    permission: bloxtools.repair
    permission-message: "§cYou don't have permission to use this command!"
  killall:
    description: Kill all mobs/entities within the server
    usage: /<command>
    permission: bloxtools.killall
    permission-message: "§cYou don't have permission to use this command!"
  broadcast:
    description: Broadcast a message in chat to all players
    usage: /<command>
    permission: bloxtools.broadcast
    permission-message: "§cYou don't have permission to use this command!"
    aliases: [bc, bcast, announcement, announce]
  whisper:
    description: Private message a user
    usage: /<command> <user> <message>
    aliases: [pm, msg, tell]
    permission: bloxtools.whisper
    permission-message: "§cYou don't have permission to use this command!"
  ping:
    description: Get your ping in miliseconds
    usage: /<command>
    permission: bloxtools.ping
    permission-message: "§cYou don't have permission to use this command!"
  hat:
    description: Put the current item in your hand in your helmet slot
    usage: /<command>
    permission: bloxtools.hat
    permission-message: "§cYou don't have permission to use this command!"
  clearinv:
    description: Clear inventory of all items
    usage: /<command> [user]
    permission: bloxtools.clearinv
    permission-message: "§cYou don't have permission to use this command!"
  smite:
    description: Smite someone with lightning
    usage: /<command> <user>
    permission: bloxtools.smite
    permission-message: "§cYou don't have permission to use this command!"