name: BloxTools
version: '1.0-SNAPSHOT'
main: me.mrbloxman.bloxtools.BloxTools
api-version: '1.20'
website: https://github.com/RandomKittenCat/BloxTools
authors: [ MrBloxMan, cats585 ]
description: Useful plugin to give you access to various commands ingame
commands:
  btinfo:
    description: Source code link and maintain information
    usage: /<command>
  heal:
    description: Heal a players hearts to full
    usage: /<command> [player]
    permission: bloxtools.heal
    permission-message: You don't have access to this command!
  gmc:
    description: Set gamemode to creative
    usage: /<command> [player]
    permission: bloxtools.creative
    permission-message: You don't have access to this command!
    aliases: [creative, gmcreative, gm1]
  gms:
    description: Set gamemode to survival
    usage: /<command> [player]
    permission: bloxtools.survival
    permission-message: You don't have access to this command!
    aliases: [survival, gmsurvival, gm2]
  gmsp:
    description: Set gamemode to spectator
    usage: /<command> [player]
    permission: bloxtools.spectator
    permission-message: You don't have access to this command!
    aliases: [spectator, gmspectator, gm3]
  kill:
    description: Kills the player specified
    usage: /<command> [player]
    permission: bloxtools.kill
    permission-message: You don't have access to this command!
  feed:
    description: Restores a players hunger bar
    usage: /<command> [player]
    permission: bloxtools.feed
    permission-message: You don't have access to this command!